name: hexlet-check

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Скачиваем код
      - uses: actions/checkout@v4

      # 2. Настраиваем Node.js (ВМЕСТО Java!)
      - uses: actions/setup-node@v4
        with:
          node-version: '20'       # Версия Node.js (20 - сейчас стандарт)
          cache: 'npm'             # (Опционально) ускоряет установку зависимостей

      # 3. Выполняем команды из Makefile
      - run: make setup
      - run: make test
      - run: make lint
